name: CI Quality Gate
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  qualitygate-pr:
    uses: ./.github/workflows/template-quality-gate-pr.yml
    secrets: inherit

  qualitygate-submodule:
    uses: ./.github/workflows/template-quality-gate-submodule.yml
    secrets: inherit